#pragma once
#include "../core.h"

class WeaponSpec
{
public:
	WeaponSpec();
	~WeaponSpec();

	float getFiringMethodChargingTimeLevel1();
	void setFiringMethodChargingTimeLevel1(float var);
	float getFiringMethodChargingTimeLevel2();
	void setFiringMethodChargingTimeLevel2(float var);
	float getFiringMethodChargingTimeLevel3();
	void setFiringMethodChargingTimeLevel3(float var);
	float getFiringMethodComboFireDelay();
	void setFiringMethodComboFireDelay(float var);
	float getFiringMethodComboValidTime();
	void setFiringMethodComboValidTime(float var);
	float getFiringMethodConsumption();
	void setFiringMethodConsumption(float var);
	float getFiringMethodConsumptionByCharging();
	void setFiringMethodConsumptionByCharging(float var);
	float getFiringMethodErrorAngle();
	void setFiringMethodErrorAngle(float var);
	float getFiringMethodFireDelay();
	void setFiringMethodFireDelay(float var);
	float getFiringMethodMaxDistance();
	void setFiringMethodMaxDistance(float var);
	float getFiringMethodMinDistance();
	void setFiringMethodMinDistance(float var);
	float getFiringMethodChargingLevel1CreateRadiateMaxNum();
	void setFiringMethodChargingLevel1CreateRadiateMaxNum(float var);
	float getFiringMethodChargingLevel2CreateRadiateMaxNum();
	void setFiringMethodChargingLevel2CreateRadiateMaxNum(float var);
	float getFiringMethodCreateRadiateMaxAngBle();
	void setFiringMethodCreateRadiateMaxAngBle(float var);
	float getFiringMethodCreateRadiateMaxNum();
	void setFiringMethodCreateRadiateMaxNum(float var);
	float getFiringMethodFiringStatMovementSpeed();
	void setFiringMethodFiringStatMovementSpeed(float var);
	float getFiringMethodFiringGaugeLevel();
	void setFiringMethodFiringGaugeLevel(float var);
	float getFiringMethodChargingLevel1CreateParallelMaxNum();
	void setFiringMethodChargingLevel1CreateParallelMaxNum(float var);
	float getFiringMethodChargingLevel2CreateParallelMaxNum();
	void setFiringMethodChargingLevel2CreateParallelMaxNum(float var);
	float getFiringMethodChargingLevel1AnimationMoveHorizon();
	void setFiringMethodChargingLevel1AnimationMoveHorizon(float var);
	float getFiringMethodChargingLevel2AnimationMoveHorizon();
	void setFiringMethodChargingLevel2AnimationMoveHorizon(float var);
	float getFiringMethodGaugeAutoRegen();
	void setFiringMethodGaugeAutoRegen(float var);
	float getRemoteAngle();
	void setRemoteAngle(float var);
	float getRemoteAttackMultiplier();
	void setRemoteAttackMultiplier(float var);
	float getRemoteDamageOnBound();
	void setRemoteDamageOnBound(float var);
	float getRemoteFOV();
	void setRemoteFOV(float var);
	float getRemoteLengthX();
	void setRemoteLengthX(float var);
	float getRemoteLengthY();
	void setRemoteLengthY(float var);
	float getRemoteMaxDistance();
	void setRemoteMaxDistance(float var);
	float getRemoteMaxScale();
	void setRemoteMaxScale(float var);
	float getRemoteMinScale();
	void setRemoteMinScale(float var);
	float getRemoteMaxSpeed();
	void setRemoteMaxSpeed(float var);
	float getRemotePenetrationCount();
	void setRemotePenetrationCount(float var);
	float getRemoteSight();
	void setRemoteSight(float var);
	float getRemoteStatusRate();
	void setRemoteStatusRate(float var);
	float getRemoteCriticalRate();
	void setRemoteCriticalRate(float var);
	float getRemoteSubBoundLenght();
	void setRemoteSubBoundLenght(float var);
	float getActionBaseParam1();
	void setActionBaseParam1(float var);
	float getStatusDistance();
	void setStatusDistance(float var);
	float getStatusRegenAndHealth();
	void setStatusRegenAndHealth(float var);
	float getStatusStatMovementSpeed();
	void setStatusStatMovementSpeed(float var);
	float getStatusStatDefence();
	void setStatusStatDefence(float var);
	float getStatusDurationTime();
	void setStatusDurationTime(float var);
	float getStatusMaxOverlapCount();
	void setStatusMaxOverlapCount(float var);
	float getStatusDotDamageMultiplier();
	void setStatusDotDamageMultiplier(float var);
	float getAttack();
	void setAttack(float var);
	float getStatAndCriticalDamage();
	void setStatAndCriticalDamage(float var);
	float getStatAndCriticalRate();
	void setStatAndCriticalRate(float var);
	
	void print(void);

private:
	float _FiringMethodChargingTimeLevel1 = 0.0f;
	float _FiringMethodChargingTimeLevel2 = 0.0f;
	float _FiringMethodChargingTimeLevel3 = 0.0f;
	float _FiringMethodComboFireDelay = 0.0f;
	float _FiringMethodComboValidTime = 0.0f;
	float _FiringMethodConsumption = 0.0f;
	float _FiringMethodConsumptionByCharging = 0.0f;
	float _FiringMethodErrorAngle = 0.0f;
	float _FiringMethodFireDelay = 0.0f;
	float _FiringMethodMaxDistance = 0.0f;
	float _FiringMethodMinDistance = 0.0f;
	float _FiringMethodChargingLevel1CreateRadiateMaxNum = 0.0f;
	float _FiringMethodChargingLevel2CreateRadiateMaxNum = 0.0f;
	float _FiringMethodCreateRadiateMaxAngBle = 0.0f;
	float _FiringMethodCreateRadiateMaxNum = 0.0f;
	float _FiringMethodFiringStatMovementSpeed = 0.0f;
	float _FiringMethodFiringGaugeLevel = 0.0f;
	float _FiringMethodChargingLevel1CreateParallelMaxNum = 0.0f;
	float _FiringMethodChargingLevel2CreateParallelMaxNum = 0.0f;
	float _FiringMethodChargingLevel1AnimationMoveHorizon = 0.0f;
	float _FiringMethodChargingLevel2AnimationMoveHorizon = 0.0f;
	float _FiringMethodGaugeAutoRegen = 0.0f;
	float _RemoteAngle = 0.0f;
	float _RemoteAttackMultiplier = 0.0f;
	float _RemoteDamageOnBound = 0.0f;
	float _RemoteFOV = 0.0f;
	float _RemoteLengthX = 0.0f;
	float _RemoteLengthY = 0.0f;
	float _RemoteMaxDistance = 0.0f;
	float _RemoteMaxScale = 0.0f;
	float _RemoteMinScale = 0.0f;
	float _RemoteMaxSpeed = 0.0f;
	float _RemotePenetrationCount = 0.0f;
	float _RemoteSight = 0.0f;
	float _RemoteStatusRate = 0.0f;
	float _RemoteCriticalRate = 0.0f;
	float _RemoteSubBoundLenght = 0.0f;
	float _ActionBaseParam1 = 0.0f;
	float _StatusDistance = 0.0f;
	float _StatusRegenAndHealth = 0.0f;
	float _StatusStatMovementSpeed = 0.0f;
	float _StatusStatDefence = 0.0f;
	float _StatusDurationTime = 0.0f;
	float _StatusMaxOverlapCount = 0.0f;
	float _StatusDotDamageMultiplier = 0.0f;
	float _Attack = 0.0f;
	float _StatAndCriticalDamage = 0.0f;
	float _StatAndCriticalRate = 0.0f;
};