// GENERATED by protocol/gen_netid_map.py -- do not edit.
//
// Canonical (== retail wire) netID  <->  MXM alpha wire netID.
// 40 client packets, 121 server packets, 19 with no alpha equivalent.

static const NetIDPair g_NetIDMapAlpha_Cl[] = {
	{ 60002, 60002 },  // CQ_FirstHello
	{ 60003, 60003 },  // CQ_UserLogin
	{ 60005, 60005 },  // ConfirmGatewayInfo
	{ 60007, 60007 },  // EnterQueue
	{ 60008, 60008 },  // CQ_Authenticate
	{ 60009, 60009 },  // CQ_AuthenticateGameServer
	{ 60014, 60014 },  // CN_ReadyToLoadCharacter
	{ 60016, 60016 },  // CN_GameMapLoaded
	{ 60021, 60021 },  // CN_ReadyToLoadGameMap
	{ 60022, 60022 },  // CN_UpdatePosition
	{ 60023, 60023 },  // CN_GamePlayerSyncActionStateOnly
	{ 60024, 60024 },  // CA_SetGameGvt
	{ 60032, 60032 },  // CQ_GameIsReady
	{ 60033, 60033 },  // CQ_LoadingComplete
	{ 60034, 60034 },  // CN_MapIsLoaded
	{ 60035, 60035 },  // ConfirmLogin
	{ 60040, 60040 },  // CQ_PlayerCastSkill
	{ 60049, 60049 },  // SetNickname
	{ 60050, 60050 },  // CheckDupNickname
	{ 60051, 60052 },  // CQ_GetCharacterInfo
	{ 60052, 60053 },  // CQ_SetLeaderCharacter
	{ 60053, 60054 },  // CQ_GamePlayerTag
	{ 60073, 60072 },  // CQ_RequestAreaPopularity
	{ 60074, 60073 },  // CQ_PartyCreate
	{ 60075, 60074 },  // CQ_PartyModify
	{ 60076, 60075 },  // CQ_PartyOptionModify
	{ 60097, 60093 },  // CQ_EnqueueGame
	{ 60100, 60096 },  // CQ_MasterPick
	{ 60101, 60097 },  // CQ_MasterUnpick
	{ 60103, 60099 },  // CQ_ReadySortieRoom
	{ 60114, 60112 },  // CN_ChannelChatMessage
	{ 60130, 60129 },  // CQ_JukeboxQueueSong
	{ 60145, 60142 },  // CQ_GetGuildProfile
	{ 60146, 60143 },  // CQ_GetGuildMemberList
	{ 60148, 60144 },  // CQ_GetGuildHistoryList
	{ 60151, 60234 },  // CQ_TierRecord
	{ 60210, 60204 },  // CQ_WhisperSend
	{ 60235, 60230 },  // CQ_LoadingProgressData
	{ 60245, 60239 },  // CQ_RTT_Time
	{ 60272, 60262 },  // CQ_RequestCalendar
};

static const NetIDPair g_NetIDMapAlpha_Sv[] = {
	{ 62002, 62002 },  // SA_FirstHello
	{ 62003, 62003 },  // SA_UserloginResult
	{ 62004, 62004 },  // SA_UserloginResult2
	{ 62005, 62005 },  // SA_AuthResult
	{ 62007, 62006 },  // SN_StationList
	{ 62009, 62008 },  // SN_TgchatServerInfo
	{ 62010, 62009 },  // SN_DoConnectGameServer
	{ 62011, 62010 },  // SN_DoConnectChannelServer
	{ 62025, 62025 },  // SN_GameCreateActor
	{ 62026, 62026 },  // SN_SpawnPosForMinimap
	{ 62028, 62028 },  // SN_GameCreateSubActor
	{ 62029, 62029 },  // SN_GameEnterActor
	{ 62030, 62030 },  // SN_GameLeaveActor
	{ 62031, 62031 },  // SN_StatusSnapshot
	{ 62033, 62033 },  // SQ_CityLobbyJoinCity
	{ 62035, 62035 },  // SN_CastSkill
	{ 62036, 62036 },  // SN_ExecuteSkill
	{ 62041, 62041 },  // SA_CastSkill
	{ 62047, 62047 },  // SA_VersionInfo
	{ 62048, 62048 },  // SN_PlayerSkillSlot
	{ 62050, 62049 },  // SN_LoadCharacterStart
	{ 62051, 62050 },  // SN_ScanEnd
	{ 62052, 62051 },  // SN_GamePlayerSyncByInt
	{ 62057, 62056 },  // SN_Money
	{ 62059, 62058 },  // SN_DestroyEntity
	{ 62060, 62059 },  // SN_SetGameGvt
	{ 62061, 62061 },  // SN_LobbyStartGame
	{ 62064, 62063 },  // SN_LoadClearedStages
	{ 62072, 62069 },  // SN_GameFieldReady
	{ 62073, 62070 },  // SA_LoadingComplete
	{ 62075, 62072 },  // SA_GameReady
	{ 62076, 62073 },  // SN_GameStart
	{ 62084, 62077 },  // SN_GamePlayerEquipWeapon
	{ 62089, 62082 },  // SN_GamePlayerStock
	{ 62090, 62083 },  // SN_PlayerStateInTown
	{ 62091, 62084 },  // SN_CityMapInfo
	{ 62097, 62090 },  // SN_SummaryInfoAll
	{ 62098, 62091 },  // SN_AvailableSummaryRewardCountList
	{ 62100, 62093 },  // SN_AchieveInfo
	{ 62101, 62094 },  // SN_AchieveLatest
	{ 62102, 62095 },  // SN_AchieveUpdate
	{ 62106, 62099 },  // SN_AccountInfo
	{ 62107, 62100 },  // SN_AccountExtraInfo
	{ 62109, 62102 },  // SN_AllCharacterBaseData
	{ 62112, 62105 },  // SN_GamePlayerTag
	{ 62113, 62106 },  // SA_GetCharacterInfo
	{ 62121, 62112 },  // SA_CheckDupNickname
	{ 62122, 62113 },  // SA_SetLeader
	{ 62123, 62114 },  // SN_LeaderCharacter
	{ 62124, 62115 },  // SN_ProfileCharacters
	{ 62125, 62116 },  // SN_ProfileItems
	{ 62126, 62117 },  // SN_ProfileWeapons
	{ 62127, 62118 },  // SN_ProfileSkills
	{ 62128, 62119 },  // SN_ProfileTitles
	{ 62129, 62120 },  // SN_ProfileMasterGears
	{ 62158, 62145 },  // SA_EnqueueGame
	{ 62173, 62152 },  // SA_AreaPopularity
	{ 62174, 62153 },  // SN_AreaPopularity
	{ 62175, 62154 },  // SA_PartyCreate
	{ 62176, 62155 },  // SA_PartyModify
	{ 62177, 62156 },  // SA_PartyOptionModify
	{ 62201, 62179 },  // SN_EnqueueMatchingQueue
	{ 62204, 62183 },  // SQ_MatchingPartyFound
	{ 62205, 62184 },  // SN_MatchingPartyGathered
	{ 62208, 62187 },  // SA_MasterPick
	{ 62209, 62188 },  // SN_MasterPick
	{ 62214, 62193 },  // SN_ReadySortieRoom
	{ 62217, 62196 },  // SN_StartCountdownSortieRoom
	{ 62218, 62197 },  // SN_SortiePrepare
	{ 62219, 62198 },  // SN_SortiePrepareBotInfo
	{ 62224, 62203 },  // SN_UpdateGameOwner
	{ 62227, 62206 },  // SN_SummaryInfoLatest
	{ 62229, 62208 },  // SN_NotifyPcDetailInfos
	{ 62238, 62218 },  // SA_ResultSpAction
	{ 62242, 62222 },  // SN_ChatChannelMessage
	{ 62257, 62236 },  // SN_FriendList
	{ 62258, 62237 },  // SN_FriendRequestList
	{ 62259, 62238 },  // SN_MutualFriendList
	{ 62261, 62240 },  // SN_BlockList
	{ 62276, 62255 },  // SN_NotifyAasRestricted
	{ 62278, 62257 },  // SN_Exp
	{ 62282, 62261 },  // SN_JukeboxEnqueuedList
	{ 62283, 62262 },  // SN_JukeboxPlay
	{ 62284, 62263 },  // SN_JukeboxHotTrackList
	{ 62299, 62276 },  // SA_GetGuildProfile
	{ 62300, 62277 },  // SA_GetGuildMemberList
	{ 62302, 62278 },  // SA_GetGuildHistoryList
	{ 62330, 62301 },  // SN_MyGuild
	{ 62338, 62309 },  // SN_GuildMemberStatus
	{ 62358, 62322 },  // SN_GuildChannelEnter
	{ 62360, 62330 },  // SN_PlayerSyncMove
	{ 62361, 62331 },  // SN_PlayerSyncTurn
	{ 62364, 62334 },  // SN_PlayerSyncActionStateOnly
	{ 62365, 62335 },  // SN_WeaponState
	{ 62390, 62361 },  // SN_ProfileCharacterSkinList
	{ 62400, 62371 },  // SN_NotifyUserLifeInfo
	{ 62404, 62376 },  // SN_WarehouseItems
	{ 62406, 62378 },  // SA_WhisperSend
	{ 62407, 62379 },  // SN_WhisperReceive
	{ 62425, 62398 },  // SN_MailUnreadNotice
	{ 62426, 62399 },  // SN_UpdateEntrySystem
	{ 62446, 62419 },  // SQ_Heartbeat
	{ 62448, 62421 },  // SN_RunClientLevelEvent
	{ 62449, 62422 },  // SN_RunClientLevelEventSeq
	{ 62450, 62423 },  // SN_LoadingProgressData
	{ 62455, 62427 },  // SN_MasterRotationInfo
	{ 62462, 62434 },  // SN_SortieCharacterSlotInfo
	{ 62465, 62437 },  // SN_SortieMasterPickPhaseStart
	{ 62466, 62438 },  // SN_SortieMasterPickPhaseEnd
	{ 62467, 62439 },  // SN_SortieMasterPickPhaseStepStart
	{ 62469, 62441 },  // SA_TierRecord
	{ 62473, 62445 },  // SN_NotifyIsInSafeZone
	{ 62474, 62446 },  // SN_NotifyIngameSkillPoint
	{ 62481, 62450 },  // SN_NotifyTimestamp
	{ 62482, 62451 },  // SA_RTT_Time
	{ 62485, 62453 },  // SN_PveComradeInfo
	{ 62500, 62467 },  // SN_ClientSettings
	{ 62525, 62489 },  // SN_AccountEquipmentList
	{ 62545, 62508 },  // SA_CalendarDetail
	{ 62575, 62535 },  // SN_InitScoreBoard
	{ 62577, 62536 },  // SN_ActionChangeLevelEvent
};

// Canonical IDs with no alpha counterpart. Sending one is a bug:
// the codec refuses and warns instead of emitting a wrong ID.
static const u16 g_NetIDAbsentAlpha[] = {
	60038,  // CN_PlayerTagCompleted            (unknown)
	60059,  // CQ_RoomEquipWeapon               (unknown)
	60071,  // CQ_RoomEquipSkill                (unknown)
	60072,  // CQ_RoomSwapSkill                 (unknown)
	60089,  // CA_SortieRoomFound               (unknown)
	60090,  // CN_SortieRoomConfirm             (unknown)
	60102,  // CQ_MasterReset                   (unknown)
	60113,  // CQ_PlayerJump                    (unknown)
	60167,  // CQ_GetGuildRankingSeasonList     (not-present)
	60178,  // CN_GameUpdatePosition            (not-present)
	60179,  // CN_GameUpdateRotation            (not-present)
	62006,  // SN_RegionServicePolicy           (not-present)
	62285,  // SN_TownHudStatistics             (not-present)
	62322,  // SA_GetGuildRankingSeasonList     (not-present)
	62468,  // SN_SortieMasterPickPhaseStep     (unknown)
	62472,  // SN_Unknown_62472                 (unknown)
	62501,  // QueueStatus                      (not-present)
	62576,  // SN_InitIngameModeInfo            (not-present)
	62601,  // SN_UpdateMasterGroupingEffect    (not-present)
};
