#include "protocol.h"

const char* ActionStateToString(ActionStateID state)
{
	if(state == ActionStateID::INVALID) return "INVALID";

	const char* s[] = {
		"ACTION_STATE_TYPE_IDLE",
		"NORMAL_STAND_MOVESTATE",
		"BATTLE_STAND_MOVESTATE",
		"NORMAL_RUN_MOVESTATE",
		"BATTLE_RUN_MOVESTATE",
		"NORMAL_RUN_FRONT_MOVESTATE",
		"BATTLE_RUN_FRONT_MOVESTATE",
		"NORMAL_RUN_LEFT_MOVESTATE",
		"BATTLE_RUN_LEFT_MOVESTATE",
		"NORMAL_RUN_RIGHT_MOVESTATE",
		"BATTLE_RUN_RIGHT_MOVESTATE",
		"NORMAL_RUN_BACK_MOVESTATE",
		"BATTLE_RUN_BACK_MOVESTATE",
		"NORMAL_ROTATE_LEFT",
		"BATTLE_ROTATE_LEFT",
		"NORMAL_ROTATE_RIGHT",
		"BATTLE_ROTATE_RIGHT",
		"MAXTYPE_MOVESTATE",
		"NONE_BEHAVIORSTATE",
		"ATTACK_BEHAVIORSTATE",
		"ATTACK1_BEHAVIORSTATE",
		"ATTACK2_BEHAVIORSTATE",
		"ATTACK3_BEHAVIORSTATE",
		"ATTACK4_BEHAVIORSTATE",
		"ATTACK5_BEHAVIORSTATE",
		"ATTACK6_BEHAVIORSTATE",
		"ATTACK7_BEHAVIORSTATE",
		"ATTACK8_BEHAVIORSTATE",
		"ATTACK9_BEHAVIORSTATE",
		"ATTACK10_BEHAVIORSTATE",
		"HIT_BEHAVIORSTATE",
		"SKILL_1_BEHAVIORSTATE",
		"SKILL_2_BEHAVIORSTATE",
		"SKILL_3_BEHAVIORSTATE",
		"SKILL_4_BEHAVIORSTATE",
		"SKILL_5_BEHAVIORSTATE",
		"SKILL_6_BEHAVIORSTATE",
		"SKILL_7_BEHAVIORSTATE",
		"SKILL_8_BEHAVIORSTATE",
		"SKILL_9_BEHAVIORSTATE",
		"SKILL_10_BEHAVIORSTATE",
		"SKILL_11_BEHAVIORSTATE",
		"SKILL_12_BEHAVIORSTATE",
		"SKILL_13_BEHAVIORSTATE",
		"SKILL_14_BEHAVIORSTATE",
		"SKILL_15_BEHAVIORSTATE",
		"SKILL_16_BEHAVIORSTATE",
		"SKILL_17_BEHAVIORSTATE",
		"SKILL_18_BEHAVIORSTATE",
		"SKILL_19_BEHAVIORSTATE",
		"SKILL_20_BEHAVIORSTATE",
		"SKILL_21_BEHAVIORSTATE",
		"SKILL_22_BEHAVIORSTATE",
		"SKILL_23_BEHAVIORSTATE",
		"SKILL_24_BEHAVIORSTATE",
		"SKILL_25_BEHAVIORSTATE",
		"SKILL_26_BEHAVIORSTATE",
		"SKILL_27_BEHAVIORSTATE",
		"SKILL_28_BEHAVIORSTATE",
		"SKILL_29_BEHAVIORSTATE",
		"SKILL_30_BEHAVIORSTATE",
		"SKILL_MAX_BEHAVIORSTATE",
		"SKILL_STAGE1_BEHAVIORSTATE",
		"SKILL_STAGE2_BEHAVIORSTATE",
		"SKILL_STAGE3_BEHAVIORSTATE",
		"SKILL_STAGE4_BEHAVIORSTATE",
		"SKILL_STAGE5_BEHAVIORSTATE",
		"SKILL_STAGE6_BEHAVIORSTATE",
		"SKILL_STAGE7_BEHAVIORSTATE",
		"SKILL_STAGE8_BEHAVIORSTATE",
		"SKILL_STAGE9_BEHAVIORSTATE",
		"SKILL_STAGE10_BEHAVIORSTATE",
		"SKILL_STAGE11_BEHAVIORSTATE",
		"SKILL_STAGE12_BEHAVIORSTATE",
		"SKILL_STAGE13_BEHAVIORSTATE",
		"SKILL_STAGE14_BEHAVIORSTATE",
		"SKILL_STAGE15_BEHAVIORSTATE",
		"SKILL_STAGE16_BEHAVIORSTATE",
		"SKILL_STAGE17_BEHAVIORSTATE",
		"SKILL_STAGE18_BEHAVIORSTATE",
		"SKILL_STAGE19_BEHAVIORSTATE",
		"SKILL_STAGE20_BEHAVIORSTATE",
		"SKILL_STAGE_MAX_BEHAVIORSTATE",
		"ATTACKCHARGE_BEHAVIORSTATE",
		"DEFEAT_FLY_BEHAVIORSTATE",
		"DEFEAT_AIRBORNE_BEHAVIORSTATE",
		"DEFEAT_PUSH_BEHAVIORSTATE",
		"DEFEAT_KNOCKDOWN_BEHAVIORSTATE",
		"DEFEAT_SYNC_BEHAVIORSTATE",
		"DEFEAT_GROGGY_BEHAVIORSTATE",
		"LIE_BEHAVIORSTATE",
		"INTERACTION_CAST_BEHAVIORSTATE",
		"INTERACTION_EXECUTE_BEHAVIORSTAT",
		"TAG_IN_EXECUTE_BEHAVIORSTATE",
		"TAG_OUT_EXECUTE_BEHAVIORSTATE",
		"STANCE_IN_BEHAVIORSTATE",
		"STANCE_OUT_BEHAVIORSTATE",
		"RELOAD_BEHAVIORSTATE",
		"WEAPONCHANGE_BEHAVIORSTATE",
		"SPAWN_BEHAVIORSTATE",
		"RESPAWN_BEHAVIORSTATE",
		"DIE_BEHAVIORSTATE",
		"UNDEAD_BEHAVIORSTATE",
		"SHIRK_BEHAVIORSTATE",
		"SHIRK_COMBO_1_BEHAVIORSTATE",
		"SHIRK_MOVE_BEHAVIORSTATE",
		"TALK_BEHAVIORSTATE",
		"BATTLE_STAND_EMOTION_BEHAVIORSTA",
		"CRAWLUP_START_BEHAVIORSTATE",
		"CRAWLUP_MOVE_BEHAVIORSTATE",
		"CRAWLUP_END_BEHAVIORSTATE",
		"CRAWLDOWN_START_BEHAVIORSTATE",
		"CRAWLDOWN_MOVE_BEHAVIORSTATE",
		"CRAWLDOWN_END_BEHAVIORSTATE",
		"JUMP_UP_BEHAVIORSTATE",
		"JUMP_DOWN_BEHAVIORSTATE",
		"EXTRAMOTION_1_BEHAVIORSTATE",
		"EXTRAMOTION_2_BEHAVIORSTATE",
		"EXTRAMOTION_3_BEHAVIORSTATE",
		"EXTRAMOTION_4_BEHAVIORSTATE",
		"EXTRAMOTION_5_BEHAVIORSTATE",
		"EXTRAMOTION_6_BEHAVIORSTATE",
		"EXTRAMOTION_7_BEHAVIORSTATE",
		"EXTRAMOTION_8_BEHAVIORSTATE",
		"EXTRAMOTION_9_BEHAVIORSTATE",
		"EXTRAMOTION_10_BEHAVIORSTATE",
		"SEQUENCE_1_BEHAVIORSTATE",
		"SEQUENCE_2_BEHAVIORSTATE",
		"SEQUENCE_3_BEHAVIORSTATE",
		"SEQUENCE_4_BEHAVIORSTATE",
		"SEQUENCE_5_BEHAVIORSTATE",
		"COMBO_1_BEHAVIORSTATE",
		"COMBO_2_BEHAVIORSTATE",
		"COMBO_3_BEHAVIORSTATE",
		"COMBO_4_BEHAVIORSTATE",
		"COMBO_5_BEHAVIORSTATE",
		"COMBO_6_BEHAVIORSTATE",
		"COMBO_7_BEHAVIORSTATE",
		"COMBO_8_BEHAVIORSTATE",
		"COMBO_9_BEHAVIORSTATE",
		"COMBO_10_BEHAVIORSTATE",
		"MELEE_1_BEHAVIORSTATE",
		"STYLISH_1_BEHAVIORSTATE",
		"CAUGHT_BEHAVIORSTATE",
		"DISABLED_BEHAVIORSTATE",
		"LIFTED_BEHAVIORSTATE",
		"PULLED_BEHAVIORSTATE",
		"DRAGGED_BEHAVIORSTATE",
		"EVENT_BEHAVIORSTATE",
		"EMOTION_BEHAVIORSTATE",
		"JUMP_LOOP_MOVESTATE",
		"BATTLE_JUMP_LOOP_MOVESTATE",
		"JUMP_START_MOVESTATE",
		"BATTLE_JUMP_START_MOVESTATE",
		"JUMP_END_MOVESTATE",
		"BATTLE_JUMP_END_MOVESTATE",
		"BREAKFALL_BEHAVIORSTATE",
		"MAXTYPE_BEHAVIORSTATE",
		"DYNAMIC_OPEN",
		"DYNAMIC_CLOSE",
		"DYNAMIC_SPAWN",
		"DYNAMIC_NORMAL_STAND",
		"DYNAMIC_BATTLE_STAND",
		"DYNAMIC_RUN_FRONT",
		"DYNAMIC_ROTATE_LEFT",
		"DYNAMIC_ROTATE_RIGHT",
		"DYNAMIC_ATTACK",
		"DYNAMIC_HIT",
		"DYNAMIC_DIE",
		"DYNAMIC_ACTIVE",
		"DYNAMIC_EXTRAMOTION_1",
		"DYNAMIC_EXTRAMOTION_2",
		"DYNAMIC_EXTRAMOTION_3",
		"ACTION_STATE_TYPE_MAX",
		"UNKNOWN_ACTION_STATE_TYPE"
	};

	i32 i = (i32)state;
	ASSERT(i >= 0 && i < ARRAY_COUNT(s));
	return s[i];
}


// TODO: could be faster
ActionStateID ActionStateFromString(const char* str)
{
	if(StringEquals(str, "ACTION_STATE_TYPE_IDLE")) {
		return ActionStateID::ACTION_STATE_TYPE_IDLE;
	}
	if(StringEquals(str, "NORMAL_STAND_MOVESTATE")) {
		return ActionStateID::NORMAL_STAND_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_STAND_MOVESTATE")) {
		return ActionStateID::BATTLE_STAND_MOVESTATE;
	}
	if(StringEquals(str, "NORMAL_RUN_MOVESTATE")) {
		return ActionStateID::NORMAL_RUN_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_RUN_MOVESTATE")) {
		return ActionStateID::BATTLE_RUN_MOVESTATE;
	}
	if(StringEquals(str, "NORMAL_RUN_FRONT_MOVESTATE")) {
		return ActionStateID::NORMAL_RUN_FRONT_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_RUN_FRONT_MOVESTATE")) {
		return ActionStateID::BATTLE_RUN_FRONT_MOVESTATE;
	}
	if(StringEquals(str, "NORMAL_RUN_LEFT_MOVESTATE")) {
		return ActionStateID::NORMAL_RUN_LEFT_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_RUN_LEFT_MOVESTATE")) {
		return ActionStateID::BATTLE_RUN_LEFT_MOVESTATE;
	}
	if(StringEquals(str, "NORMAL_RUN_RIGHT_MOVESTATE")) {
		return ActionStateID::NORMAL_RUN_RIGHT_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_RUN_RIGHT_MOVESTATE")) {
		return ActionStateID::BATTLE_RUN_RIGHT_MOVESTATE;
	}
	if(StringEquals(str, "NORMAL_RUN_BACK_MOVESTATE")) {
		return ActionStateID::NORMAL_RUN_BACK_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_RUN_BACK_MOVESTATE")) {
		return ActionStateID::BATTLE_RUN_BACK_MOVESTATE;
	}
	if(StringEquals(str, "NORMAL_ROTATE_LEFT")) {
		return ActionStateID::NORMAL_ROTATE_LEFT;
	}
	if(StringEquals(str, "BATTLE_ROTATE_LEFT")) {
		return ActionStateID::BATTLE_ROTATE_LEFT;
	}
	if(StringEquals(str, "NORMAL_ROTATE_RIGHT")) {
		return ActionStateID::NORMAL_ROTATE_RIGHT;
	}
	if(StringEquals(str, "BATTLE_ROTATE_RIGHT")) {
		return ActionStateID::BATTLE_ROTATE_RIGHT;
	}
	if(StringEquals(str, "MAXTYPE_MOVESTATE")) {
		return ActionStateID::MAXTYPE_MOVESTATE;
	}
	if(StringEquals(str, "NONE_BEHAVIORSTATE")) {
		return ActionStateID::NONE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK1_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK2_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK2_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK3_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK3_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK4_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK4_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK5_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK5_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK6_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK6_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK7_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK7_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK8_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK8_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK9_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK9_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACK10_BEHAVIORSTATE")) {
		return ActionStateID::ATTACK10_BEHAVIORSTATE;
	}
	if(StringEquals(str, "HIT_BEHAVIORSTATE")) {
		return ActionStateID::HIT_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_1_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_2_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_2_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_3_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_3_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_4_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_4_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_5_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_5_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_6_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_6_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_7_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_7_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_8_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_8_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_9_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_9_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_10_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_10_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_11_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_11_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_12_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_12_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_13_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_13_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_14_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_14_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_15_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_15_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_16_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_16_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_17_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_17_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_18_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_18_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_19_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_19_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_20_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_20_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_21_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_21_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_22_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_22_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_23_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_23_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_24_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_24_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_25_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_25_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_26_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_26_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_27_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_27_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_28_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_28_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_29_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_29_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_30_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_30_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_MAX_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_MAX_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE1_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE2_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE2_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE3_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE3_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE4_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE4_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE5_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE5_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE6_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE6_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE7_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE7_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE8_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE8_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE9_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE9_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE10_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE10_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE11_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE11_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE12_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE12_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE13_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE13_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE14_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE14_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE15_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE15_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE16_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE16_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE17_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE17_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE18_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE18_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE19_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE19_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE20_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE20_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SKILL_STAGE_MAX_BEHAVIORSTATE")) {
		return ActionStateID::SKILL_STAGE_MAX_BEHAVIORSTATE;
	}
	if(StringEquals(str, "ATTACKCHARGE_BEHAVIORSTATE")) {
		return ActionStateID::ATTACKCHARGE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DEFEAT_FLY_BEHAVIORSTATE")) {
		return ActionStateID::DEFEAT_FLY_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DEFEAT_AIRBORNE_BEHAVIORSTATE")) {
		return ActionStateID::DEFEAT_AIRBORNE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DEFEAT_PUSH_BEHAVIORSTATE")) {
		return ActionStateID::DEFEAT_PUSH_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DEFEAT_KNOCKDOWN_BEHAVIORSTATE")) {
		return ActionStateID::DEFEAT_KNOCKDOWN_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DEFEAT_SYNC_BEHAVIORSTATE")) {
		return ActionStateID::DEFEAT_SYNC_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DEFEAT_GROGGY_BEHAVIORSTATE")) {
		return ActionStateID::DEFEAT_GROGGY_BEHAVIORSTATE;
	}
	if(StringEquals(str, "LIE_BEHAVIORSTATE")) {
		return ActionStateID::LIE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "INTERACTION_CAST_BEHAVIORSTATE")) {
		return ActionStateID::INTERACTION_CAST_BEHAVIORSTATE;
	}
	if(StringEquals(str, "INTERACTION_EXECUTE_BEHAVIORSTAT")) {
		return ActionStateID::INTERACTION_EXECUTE_BEHAVIORSTAT;
	}
	if(StringEquals(str, "TAG_IN_EXECUTE_BEHAVIORSTATE")) {
		return ActionStateID::TAG_IN_EXECUTE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "TAG_OUT_EXECUTE_BEHAVIORSTATE")) {
		return ActionStateID::TAG_OUT_EXECUTE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "STANCE_IN_BEHAVIORSTATE")) {
		return ActionStateID::STANCE_IN_BEHAVIORSTATE;
	}
	if(StringEquals(str, "STANCE_OUT_BEHAVIORSTATE")) {
		return ActionStateID::STANCE_OUT_BEHAVIORSTATE;
	}
	if(StringEquals(str, "RELOAD_BEHAVIORSTATE")) {
		return ActionStateID::RELOAD_BEHAVIORSTATE;
	}
	if(StringEquals(str, "WEAPONCHANGE_BEHAVIORSTATE")) {
		return ActionStateID::WEAPONCHANGE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SPAWN_BEHAVIORSTATE")) {
		return ActionStateID::SPAWN_BEHAVIORSTATE;
	}
	if(StringEquals(str, "RESPAWN_BEHAVIORSTATE")) {
		return ActionStateID::RESPAWN_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DIE_BEHAVIORSTATE")) {
		return ActionStateID::DIE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "UNDEAD_BEHAVIORSTATE")) {
		return ActionStateID::UNDEAD_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SHIRK_BEHAVIORSTATE")) {
		return ActionStateID::SHIRK_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SHIRK_COMBO_1_BEHAVIORSTATE")) {
		return ActionStateID::SHIRK_COMBO_1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SHIRK_MOVE_BEHAVIORSTATE")) {
		return ActionStateID::SHIRK_MOVE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "TALK_BEHAVIORSTATE")) {
		return ActionStateID::TALK_BEHAVIORSTATE;
	}
	if(StringEquals(str, "BATTLE_STAND_EMOTION_BEHAVIORSTA")) {
		return ActionStateID::BATTLE_STAND_EMOTION_BEHAVIORSTA;
	}
	if(StringEquals(str, "CRAWLUP_START_BEHAVIORSTATE")) {
		return ActionStateID::CRAWLUP_START_BEHAVIORSTATE;
	}
	if(StringEquals(str, "CRAWLUP_MOVE_BEHAVIORSTATE")) {
		return ActionStateID::CRAWLUP_MOVE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "CRAWLUP_END_BEHAVIORSTATE")) {
		return ActionStateID::CRAWLUP_END_BEHAVIORSTATE;
	}
	if(StringEquals(str, "CRAWLDOWN_START_BEHAVIORSTATE")) {
		return ActionStateID::CRAWLDOWN_START_BEHAVIORSTATE;
	}
	if(StringEquals(str, "CRAWLDOWN_MOVE_BEHAVIORSTATE")) {
		return ActionStateID::CRAWLDOWN_MOVE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "CRAWLDOWN_END_BEHAVIORSTATE")) {
		return ActionStateID::CRAWLDOWN_END_BEHAVIORSTATE;
	}
	if(StringEquals(str, "JUMP_UP_BEHAVIORSTATE")) {
		return ActionStateID::JUMP_UP_BEHAVIORSTATE;
	}
	if(StringEquals(str, "JUMP_DOWN_BEHAVIORSTATE")) {
		return ActionStateID::JUMP_DOWN_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_1_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_2_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_2_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_3_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_3_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_4_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_4_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_5_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_5_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_6_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_6_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_7_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_7_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_8_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_8_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_9_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_9_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EXTRAMOTION_10_BEHAVIORSTATE")) {
		return ActionStateID::EXTRAMOTION_10_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SEQUENCE_1_BEHAVIORSTATE")) {
		return ActionStateID::SEQUENCE_1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SEQUENCE_2_BEHAVIORSTATE")) {
		return ActionStateID::SEQUENCE_2_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SEQUENCE_3_BEHAVIORSTATE")) {
		return ActionStateID::SEQUENCE_3_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SEQUENCE_4_BEHAVIORSTATE")) {
		return ActionStateID::SEQUENCE_4_BEHAVIORSTATE;
	}
	if(StringEquals(str, "SEQUENCE_5_BEHAVIORSTATE")) {
		return ActionStateID::SEQUENCE_5_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_1_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_2_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_2_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_3_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_3_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_4_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_4_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_5_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_5_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_6_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_6_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_7_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_7_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_8_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_8_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_9_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_9_BEHAVIORSTATE;
	}
	if(StringEquals(str, "COMBO_10_BEHAVIORSTATE")) {
		return ActionStateID::COMBO_10_BEHAVIORSTATE;
	}
	if(StringEquals(str, "MELEE_1_BEHAVIORSTATE")) {
		return ActionStateID::MELEE_1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "STYLISH_1_BEHAVIORSTATE")) {
		return ActionStateID::STYLISH_1_BEHAVIORSTATE;
	}
	if(StringEquals(str, "CAUGHT_BEHAVIORSTATE")) {
		return ActionStateID::CAUGHT_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DISABLED_BEHAVIORSTATE")) {
		return ActionStateID::DISABLED_BEHAVIORSTATE;
	}
	if(StringEquals(str, "LIFTED_BEHAVIORSTATE")) {
		return ActionStateID::LIFTED_BEHAVIORSTATE;
	}
	if(StringEquals(str, "PULLED_BEHAVIORSTATE")) {
		return ActionStateID::PULLED_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DRAGGED_BEHAVIORSTATE")) {
		return ActionStateID::DRAGGED_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EVENT_BEHAVIORSTATE")) {
		return ActionStateID::EVENT_BEHAVIORSTATE;
	}
	if(StringEquals(str, "EMOTION_BEHAVIORSTATE")) {
		return ActionStateID::EMOTION_BEHAVIORSTATE;
	}
	if(StringEquals(str, "JUMP_LOOP_MOVESTATE")) {
		return ActionStateID::JUMP_LOOP_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_JUMP_LOOP_MOVESTATE")) {
		return ActionStateID::BATTLE_JUMP_LOOP_MOVESTATE;
	}
	if(StringEquals(str, "JUMP_START_MOVESTATE")) {
		return ActionStateID::JUMP_START_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_JUMP_START_MOVESTATE")) {
		return ActionStateID::BATTLE_JUMP_START_MOVESTATE;
	}
	if(StringEquals(str, "JUMP_END_MOVESTATE")) {
		return ActionStateID::JUMP_END_MOVESTATE;
	}
	if(StringEquals(str, "BATTLE_JUMP_END_MOVESTATE")) {
		return ActionStateID::BATTLE_JUMP_END_MOVESTATE;
	}
	if(StringEquals(str, "BREAKFALL_BEHAVIORSTATE")) {
		return ActionStateID::BREAKFALL_BEHAVIORSTATE;
	}
	if(StringEquals(str, "MAXTYPE_BEHAVIORSTATE")) {
		return ActionStateID::MAXTYPE_BEHAVIORSTATE;
	}
	if(StringEquals(str, "DYNAMIC_OPEN")) {
		return ActionStateID::DYNAMIC_OPEN;
	}
	if(StringEquals(str, "DYNAMIC_CLOSE")) {
		return ActionStateID::DYNAMIC_CLOSE;
	}
	if(StringEquals(str, "DYNAMIC_SPAWN")) {
		return ActionStateID::DYNAMIC_SPAWN;
	}
	if(StringEquals(str, "DYNAMIC_NORMAL_STAND")) {
		return ActionStateID::DYNAMIC_NORMAL_STAND;
	}
	if(StringEquals(str, "DYNAMIC_BATTLE_STAND")) {
		return ActionStateID::DYNAMIC_BATTLE_STAND;
	}
	if(StringEquals(str, "DYNAMIC_RUN_FRONT")) {
		return ActionStateID::DYNAMIC_RUN_FRONT;
	}
	if(StringEquals(str, "DYNAMIC_ROTATE_LEFT")) {
		return ActionStateID::DYNAMIC_ROTATE_LEFT;
	}
	if(StringEquals(str, "DYNAMIC_ROTATE_RIGHT")) {
		return ActionStateID::DYNAMIC_ROTATE_RIGHT;
	}
	if(StringEquals(str, "DYNAMIC_ATTACK")) {
		return ActionStateID::DYNAMIC_ATTACK;
	}
	if(StringEquals(str, "DYNAMIC_HIT")) {
		return ActionStateID::DYNAMIC_HIT;
	}
	if(StringEquals(str, "DYNAMIC_DIE")) {
		return ActionStateID::DYNAMIC_DIE;
	}
	if(StringEquals(str, "DYNAMIC_ACTIVE")) {
		return ActionStateID::DYNAMIC_ACTIVE;
	}
	if(StringEquals(str, "DYNAMIC_EXTRAMOTION_1")) {
		return ActionStateID::DYNAMIC_EXTRAMOTION_1;
	}
	if(StringEquals(str, "DYNAMIC_EXTRAMOTION_2")) {
		return ActionStateID::DYNAMIC_EXTRAMOTION_2;
	}
	if(StringEquals(str, "DYNAMIC_EXTRAMOTION_3")) {
		return ActionStateID::DYNAMIC_EXTRAMOTION_3;
	}
	if(StringEquals(str, "ACTION_STATE_TYPE_MAX")) {
		return ActionStateID::ACTION_STATE_TYPE_MAX;
	}
	if(StringEquals(str, "UNKNOWN_ACTION_STATE_TYPE")) {
		return ActionStateID::UNKNOWN_ACTION_STATE_TYPE;
	}

	return ActionStateID::INVALID;
}
