#pragma once
#include <common/base.h>

/*
 Client-build support.

 The server's netIDs (protocol.h `enum { NET_ID = N }`) are CANONICAL. They
 happen to equal the retail client's wire IDs, so retail is the identity
 mapping and cannot regress -- but do not think of canonical as "retail".
 A future build will have packets neither alpha nor retail has, and those get
 canonical IDs from a private range rather than forcing a renumber.

 Only 36 of the server's 180 packets keep their number in the alpha, so a
 translation is mandatory. It happens at the socket edge and nowhere else:

   inbound   ToCanonical()  right after the NetHeader is read off the wire,
                            before any switch(header.netID)
   outbound  ToWire()       inside Server::SendPacketData / the login server's
                            own SendPacketData

 Everything between those two points -- all 180 structs, all the
 `case Cl::X::NET_ID:` labels, every handler -- stays canonical and needs no
 version awareness.

 Server<->server traffic (namespace In, InnerConnection::SendPacketData, the
 matchmaker packet queue) is NOT translated. It never leaves our own process
 group, so it has no client build. Keep it that way.

 Table generated by protocol/gen_netid_map.py from protocol/netid_alpha.json;
 regenerate after touching either.
*/

enum class ClientVersion : i32
{
	RETAIL = 0,	// 1.17.1017.9146, 2017-10-16. Canonical; identity mapping.
	ALPHA  = 1,	// 0.960.813.8401, 2016-08-13.

	_COUNT
};

// Canonical IDs for packets that exist in some build but not in retail are
// allocated from here, so no build's numbering is privileged.
enum { CANON_PRIVATE_BASE = 1000 };

// Returned by ToWire() when the target build has no equivalent packet. The
// caller must drop the packet: putting netID 0 on the wire would be a
// well-formed packet that says nothing, and the client swallows those silently.
enum { NETID_ABSENT = 0 };

struct NetIDPair
{
	u16 canon;
	u16 wire;
};

#include "netid_map_alpha.inl"

// Canonical IDs that map to a real alpha packet, but whose alpha field layout
// has not been recovered, so we cannot fill them in correctly. Hand-maintained
// (the generator only knows about netIDs, not layouts).
//
// Empty for now. SQ_MatchingPartyFound (62204) used to live here: it was the
// first packet found whose ID mapped correctly but whose layout did not, and it
// killed the client with
//   [TLFATAL] Serialization error on received packet:SQ_MATCHING_PARTY_FOUND
// Its layout has since been recovered from the deserializer at 0x821df0 -- the
// alpha's Player entry simply has no isBot byte -- so it is sent for real again.
// See HubReplication::SendMatchingPartyFound.
static const u16 g_NetIDLayoutUnknownAlpha[] = { 0 };  // 0 is never a valid netID

const char* ClientVersionName(ClientVersion v);
ClientVersion ClientVersionFromString(const char* str);

// Fingerprint of the alpha's CQ_FirstHello. The client sends its own protocol
// and error CRCs in the very first packet, and netID 60002 is one of the 36
// that did not move -- so the first packet is readable in either dialect and
// can identify the build before anything else is sent.
enum : u32 {
	ALPHA_PROTOCOL_CRC = 0x0145f8bc,
	ALPHA_ERROR_CRC    = 0x303fab2d,
	ALPHA_VERSION      = 0xb5ae2865,
};

// CQ_FirstHello is 13 bytes in retail (trailing `u8 unknown`) and 12 in the
// alpha, which is a second, independent discriminator.
enum { ALPHA_FIRST_HELLO_SIZE = 12 };

ClientVersion DetectClientVersion(u32 protocolCRC, u32 errorCRC, u32 version, i32 packetSize);

/*
 One codec per connection. Cheap to copy; holds no state beyond the build.

 Per-connection rather than per-server on purpose: it is what lets a retail and
 an alpha client be served at once, which is also the only way to regression
 test retail while developing against the alpha.
*/
struct ProtocolCodec
{
	ClientVersion version = ClientVersion::RETAIL;

	ProtocolCodec() = default;
	explicit ProtocolCodec(ClientVersion v): version(v) {}

	// wire -> canonical, for received client packets.
	// Unknown IDs pass through unchanged so they still reach the dispatch
	// default and get logged as unhandled, rather than vanishing here.
	inline u16 ToCanonical(u16 wireID) const
	{
		if(version == ClientVersion::RETAIL) return wireID;
		return Lookup(g_NetIDMapAlpha_Cl, ARRAY_COUNT(g_NetIDMapAlpha_Cl), wireID, false, wireID);
	}

	// canonical -> wire, for server packets we are about to send.
	// Returns NETID_ABSENT if this build has no such packet; the caller MUST
	// drop it rather than send a wrong or zero ID.
	inline u16 ToWire(u16 canonID) const
	{
		if(version == ClientVersion::RETAIL) return canonID;
		if(IsAbsent(canonID)) return NETID_ABSENT;
		// An unmapped ID is a table gap, not a passthrough: sending retail's
		// number to an alpha client would land on some unrelated packet.
		return Lookup(g_NetIDMapAlpha_Sv, ARRAY_COUNT(g_NetIDMapAlpha_Sv), canonID, true, NETID_ABSENT);
	}

	inline bool IsAbsent(u16 canonID) const
	{
		if(version == ClientVersion::RETAIL) return false;
		for(i32 i = 0; i < (i32)ARRAY_COUNT(g_NetIDAbsentAlpha); i++) {
			if(g_NetIDAbsentAlpha[i] == canonID) return true;
		}
		// Packets whose netID we know but whose alpha LAYOUT we have not
		// recovered. Deliberately a different thing from being absent: the
		// packet exists, we simply cannot serialise it correctly yet, and the
		// client kills itself on a malformed one ([TLFATAL] Serialization
		// error) while it tolerates never receiving it at all. Recover the
		// layout with protocol/alpha_layout.py, then delete the entry.
		for(i32 i = 0; i < (i32)ARRAY_COUNT(g_NetIDLayoutUnknownAlpha); i++) {
			if(g_NetIDLayoutUnknownAlpha[i] == canonID) return true;
		}
		return false;
	}

	// --- per-build layout and constant deltas ------------------------------
	// Small enough to keep as predicates rather than variant structs. Every
	// one is confirmed against the live client; see NETWORKING.md.

	// SA_FirstHello has no tqosWorldId in the alpha. The string does not occur
	// anywhere in the alpha image in either encoding.
	inline bool HasTqosWorldId() const { return version == ClientVersion::RETAIL; }

	// SA_FirstHello.clientIp goes on the wire reversed. The hub coordinator
	// already does this unconditionally; the login server did not, and only the
	// alpha is known to need it -- so it stays alpha-only rather than silently
	// changing retail's bytes.
	inline bool ClientIpIsReversed() const { return version == ClientVersion::ALPHA; }

	// SA_UserloginResult accept value. The alpha's handler at 0x0063a706 is
	// `cmp eax,0x31 / jne`, and reports failure as N23<nResult-0x31>.
	inline i32 UserLoginAccept() const { return version == ClientVersion::ALPHA ? 0x31 : 0x33; }

	// SA_AuthResult accept value: `sub eax,0x55` at 0x008c6179.
	inline i32 AuthAccept() const { return version == ClientVersion::ALPHA ? 0x55 : 91; }

	// SN_AccountInfo gained activityPoint (i32) + activityRewardedState (u8)
	// after badgeType. Retail's struct stops 5 bytes short, which is fatal for
	// the alpha -- it raises [TLFATAL] Serialization error and exits.
	inline bool AccountInfoHasActivity() const { return version == ClientVersion::ALPHA; }

	// Retail inserted a `staffType` u8 BETWEEN the two strings of the chat
	// packets. The alpha has no such field, and because it sits between two
	// variable-length strings the extra byte does not merely add junk -- it
	// shifts the second string's u16 length by one, so the client reads a
	// nonsense length and then decodes the text one byte out of phase. "aaaa"
	// arrives as the CJK run U+6100 U+6100 ... (bytes 61 00 read as 00 61).
	//
	// Deserializers, all confirmed:
	//   SN_CHAT_CHANNEL_MESSAGE 0x815b8d  i32, wstring, wstring
	//   SN_WHISPER_RECEIVED     0x821d31  wstring, wstring
	//   SA_WHISPER_SEND         0x813858  i32, wstring, wstring  (already right)
	//
	// Note this also retires the claim in NETWORKING.md that the alpha's
	// SN_CHAT_CHANNEL_MESSAGE has a trailing seasonId: the deserializer returns
	// after the second string and never reads one. pyserver sends it and gets
	// away with it only because trailing bytes are ignored.
	inline bool ChatHasStaffType() const { return version == ClientVersion::RETAIL; }

	// Both halves of the set-leader exchange carry a classType the retail
	// structs lack, inserted before skinIndex:
	//   CQ_SET_LEADER  characterID, classType, skinIndex   (12 B, retail 8)
	//   SA_SET_LEADER  result, leaderID, classType, skinIndex (16 B, retail 12)
	// Outbound, retail's 12 bytes are one dword short and the client exits on
	// it. Inbound, retail's struct silently reads classType as skinIndex, so
	// the master changes with the wrong skin and nothing looks broken.
	inline bool SetLeaderHasClassType() const { return version == ClientVersion::ALPHA; }

	// SQ_MatchingPartyFound's per-player entry has no isBot byte in the alpha.
	// Same shape of delta as the chat staffType: a u8 retail inserted into the
	// middle of a structure, so it desynchronises everything after it.
	inline bool PlayerHasIsBot() const { return version == ClientVersion::RETAIL; }

private:
	static inline u16 Lookup(const NetIDPair* table, i32 count, u16 key, bool byCanon, u16 fallback)
	{
		// Both tables are sorted on `canon` by the generator, but the Cl table
		// is searched by `wire`, which is not sorted. Linear is fine: 40 and
		// 121 entries, and this is not on any hot path.
		for(i32 i = 0; i < count; i++) {
			const u16 k = byCanon ? table[i].canon : table[i].wire;
			if(k == key) return byCanon ? table[i].wire : table[i].canon;
		}
		return fallback;
	}
};
